#!/usr/bin/with-contenv bash

set -xe

while ! wlr-randr >/dev/null 2>&1; do
sleep 1
done

exec s6-setuidgid $USER \
  sunshine \
    origin_web_ui_allowed=wan \
    port=$SUNSHINE_PORT \
    file_apps=/etc/sunshine/apps.json \
    upnp=off $SUNSHINE_EXTRA_ARGS