#!/usr/bin/with-contenv bash

set -xe

mkdir -p $HOME $XDG_RUNTIME_DIR
chown $UID:$UID $HOME $XDG_RUNTIME_DIR

useradd $USER -d $HOME -m -u $UID
usermod -G wheel,video,input,render,dbus,seat $USER

s6-setuidgid $USER \
  cp -r /etc/skel/. $HOME

# sunshine
s6-setuidgid $USER \
  sunshine --creds $SUNSHINE_USERNAME $SUNSHINE_PASSWORD