#!/usr/bin/with-contenv bash

set -xe

mkdir -p $HOME/nvidia

driver_version=$(nvidia-smi --query-gpu=driver_version --format=csv,noheader --id=0)
driver_file=$HOME/nvidia/NVIDIA-Linux-$(arch)-${driver_version}.run

if [[ ! -f "$driver_file" ]]; then
  curl -L -o $driver_file \
    $NVIDIA_DRIVER_BASE_URL/${driver_version}/NVIDIA-Linux-$(arch)-${driver_version}.run
fi

chmod +x $driver_file

"$driver_file" \
  --silent \
  --accept-license \
  --skip-depmod \
  --skip-module-unload \
  --no-kernel-modules \
  --no-kernel-module-source \
  --install-compat32-libs \
  --no-nouveau-check \
  --no-nvidia-modprobe \
  --no-systemd \
  --no-distro-scripts \
  --no-rpms \
  --no-backup \
  --no-check-for-alternate-installs \
  --no-libglx-indirect \
  --no-install-libglvnd

nvidia-xconfig \
  --depth="$COLOR_DEPTH" \
  --allow-empty-initial-configuration \
  --no-probe-all-gpus \
  --egpu \
  --no-sli \
  --no-base-mosaic \
  --only-one-x-screen \
  --use-display-device=$DISPLAY_DEVICE

cat > /etc/X11/xorg.conf.d/50-custom.conf <<EOF
Section "Screen"
    Identifier "Screen0"
    Monitor    "Monitor0"
    Option     "ConnectedMonitor" "$DISPLAY_DEVICE"
    Option     "ModeValidation" "NoMaxPClkCheck,NoEdidMaxPClkCheck,NoMaxSizeCheck,NoHorizSyncCheck,NoVertRefreshCheck,NoVirtualSizeCheck,NoTotalSizeCheck,NoDualLinkDVICheck,NoDisplayPortBandwidthCheck,AllowNon3DVisionModes,AllowNonHDMI3DModes,AllowNonEdidModes,NoEdidHDMI2Check,AllowDpInterlaced"
EndSection

Section "InputClass"
    Identifier "libinput pointer catchall"
    Option     "AccelProfile" "flat"
EndSection
EOF